### ISSUE TITLE
exception on GET request

### ISSUE THREAD

**Issue by try2codesecure** [lekpamartin/uptimerobot_exporter#1]
I tried to get the exporter up & running but on datasource creation (save & test) in prometheus i get an exception:
I'm using the "lekpamartin/uptimerobot_exporter:latest" image.

----------------------------------------
Exception happened during processing of request from ('172.30.0.7', 57568)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 414, in handle_one_request
    method()
  File "/exporter.py", line 112, in do_GET
    answer = fetch_data(api_key)
  File "/exporter.py", line 27, in fetch_data
    return req.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
----------------------------------------
172.30.0.7 - - [20/Nov/2019 16:00:13] code 501, message Unsupported method ('POST')
172.30.0.7 - - [20/Nov/2019 16:00:13] "POST /api/v1/query HTTP/1.1" 501 -
172.30.0.7 - - [20/Nov/2019 16:00:14] code 501, message Unsupported method ('POST')
172.30.0.7 - - [20/Nov/2019 16:00:14] "POST /api/v1/query HTTP/1.1" 501 -
----------------------------------------

The POST request seems fine, so i thought my config is right.

**Comment by lekpamartin** [comment]
Hi,

Sorry for the late. 

In the webUI of uptimerobot_exporter do you have data? 

Thx
