### ISSUE TITLE
Works for a few seconds, then errors

### ISSUE THREAD

**Issue by craigmate** [lekpamartin/uptimerobot_exporter#20]
HI.  I have setup this docker container, however I am getting the following error:

Exception occurred during processing of request from ('172.28.0.1', 42772)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request

    method()
  File "/exporter.py", line 147, in do_GET
    answer = fetch_data(api_key)
             ^^^^^^^^^^^^^^^^^^^
  File "/exporter.py", line 58, in fetch_data
    for monitor in response["monitors"]:
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'monitors'
----------------------------------------

the 172 IP is the prometheus server. 
The strange thing is if I restart the docker, it might work briefly, (website loads) but after a few seconds, it stops. 

I have tried change the tcp port, increasing the docker version, but nothing seems to work, i have also tried setting up the read-only api and monitor-specific api, but they don't seem to work as well.

One interesting thing which is might be is that uptime-robot is stopping the API from connecting, since I have uptime-robot running in home assistant, and it goes offline as well. 

Any idea what else I could try.
Thank You

**Comment by jiayuchen888** [comment]
Hey, We have the same problem, and after testing with the REST api command(https://uptimerobot.com/api/), we found that the issue comes from this parameter:
https://github.com/lekpamartin/uptimerobot_exporter/blob/master/files/exporter.py#L44

You can try removing this line, building a docker image en local, and testing with your api key.  It works better.
